use rpmbuild with a wrapper script to apply --macros flag
- backport of 5250a6623e846e64c2ea3237213a0018ea7c8324
- On SLES, the package uses %service_del_preun and %service_del_postun macros
  which remain unexpanded, resulting in scriptlet failures during package
  removal on SLES15:

    error: %preun(openvox-server) scriptlet failed, exit status 1
    /var/tmp/rpm-tmp.XXX: line 1: fg: no job control

- use wrapper rpmbuild script to allow --macros flag

    fpm does not expose --macros flag when calling rpmbuild, so we will
    use a wrapper (only for SLES builds) to point to SUSE-specific RPM
    macros

Signed-off-by: Corporate Gadfly <haroon.rafique@gmail.com>