add missing BuildRequires: systemd-rpm-macros
On SLES, the package uses %service_del_preun and %service_del_postun macros
but doesn't declare systemd-rpm-macros as a build dependency.

This causes the macros to be incorrectly expanded or missing,
resulting in scriptlet failures during package removal on SLES15:

  error: %preun(openvox-server) scriptlet failed, exit status 1
  /var/tmp/rpm-tmp.XXX: line 1: fg: no job control

Adding the BuildRequires ensures the macros are properly defined
during package build.

Signed-off-by: Corporate Gadfly <haroon.rafique@gmail.com>